# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\LRK\python\ghelper-qt\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home(object):
    def setupUi(self, home):
        home.setObjectName("Ui_home")
        home.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(home)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 8, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.SubtitleLabel_2 = SubtitleLabel(self.centralwidget)
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.gridLayout.addWidget(self.SubtitleLabel_2, 5, 2, 1, 1)
        self.LargeTitleLabel = LargeTitleLabel(self.centralwidget)
        self.LargeTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")
        self.gridLayout.addWidget(self.LargeTitleLabel, 0, 2, 1, 1)
        self.TitleLabel = TitleLabel(self.centralwidget)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 2, 2, 1, 1)
        self.TitleLabel_2 = TitleLabel(self.centralwidget)
        self.TitleLabel_2.setObjectName("TitleLabel_2")
        self.gridLayout.addWidget(self.TitleLabel_2, 4, 2, 1, 1)
        self.SubtitleLabel = SubtitleLabel(self.centralwidget)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.gridLayout.addWidget(self.SubtitleLabel, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 7, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 5, 1, 1, 1)
        home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 19))
        self.menubar.setObjectName("menubar")
        home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(home)
        self.statusbar.setObjectName("statusbar")
        home.setStatusBar(self.statusbar)

        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, Ui_home):
        _translate = QtCore.QCoreApplication.translate
        Ui_home.setWindowTitle(_translate("Ui_home", "MainWindow"))
        self.SubtitleLabel_2.setText(_translate("Ui_home", "由 星光light 维护，开源免费。"))
        self.LargeTitleLabel.setText(_translate("Ui_home", "ghelper"))
        self.TitleLabel.setText(_translate("Ui_home", "快速使用"))
        self.TitleLabel_2.setText(_translate("Ui_home", "关于本项目"))
        self.SubtitleLabel.setText(_translate("Ui_home", "点击侧边栏的按钮选择对应项目"))
from qfluentwidgets import LargeTitleLabel, SubtitleLabel, TitleLabel
