# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\LRK\python\ghelper-qt\problem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_problem(object):
    def setupUi(self, problem):
        problem.setObjectName("problem")
        problem.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(problem)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Jump_down = TransparentPushButton(self.centralwidget)
        self.Jump_down.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Jump_down.setObjectName("Jump_down")
        self.gridLayout.addWidget(self.Jump_down, 2, 3, 1, 2)
        self.Choose_all = PrimaryPushButton(self.centralwidget)
        self.Choose_all.setObjectName("Choose_all")
        self.gridLayout.addWidget(self.Choose_all, 0, 3, 1, 1)
        self.Problem_download = PrimaryPushButton(self.centralwidget)
        self.Problem_download.setObjectName("Problem_download")
        self.gridLayout.addWidget(self.Problem_download, 2, 5, 1, 1)
        self.Search_problem = SearchLineEdit(self.centralwidget)
        self.Search_problem.setObjectName("Search_problem")
        self.gridLayout.addWidget(self.Search_problem, 0, 0, 1, 3)
        self.Jump_page = CompactSpinBox(self.centralwidget)
        self.Jump_page.setObjectName("Jump_page")
        self.gridLayout.addWidget(self.Jump_page, 2, 2, 1, 1)
        self.ProgressBar = ProgressBar(self.centralwidget)
        self.ProgressBar.setMaximumSize(QtCore.QSize(350, 4))
        self.ProgressBar.setObjectName("ProgressBar")
        self.gridLayout.addWidget(self.ProgressBar, 2, 6, 1, 1)
        self.Jump_up = TransparentPushButton(self.centralwidget)
        self.Jump_up.setObjectName("Jump_up")
        self.gridLayout.addWidget(self.Jump_up, 2, 0, 1, 1)
        self.Jump = TransparentPushButton(self.centralwidget)
        self.Jump.setObjectName("Jump")
        self.gridLayout.addWidget(self.Jump, 2, 1, 1, 1)
        self.Choose_reverse = PrimaryPushButton(self.centralwidget)
        self.Choose_reverse.setObjectName("Choose_reverse")
        self.gridLayout.addWidget(self.Choose_reverse, 0, 4, 1, 1)
        self.Problem = QtWidgets.QTableWidget(self.centralwidget)
        self.Problem.setObjectName("Problem")
        self.Problem.setColumnCount(0)
        self.Problem.setRowCount(0)
        self.gridLayout.addWidget(self.Problem, 1, 0, 1, 7)
        problem.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(problem)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        problem.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(problem)
        self.statusbar.setObjectName("statusbar")
        problem.setStatusBar(self.statusbar)

        self.retranslateUi(problem)
        QtCore.QMetaObject.connectSlotsByName(problem)

    def retranslateUi(self, problem):
        _translate = QtCore.QCoreApplication.translate
        problem.setWindowTitle(_translate("problem", "MainWindow"))
        self.Jump_down.setText(_translate("problem", "下一页"))
        self.Choose_all.setText(_translate("problem", "全选"))
        self.Problem_download.setText(_translate("problem", "下载"))
        self.Jump_up.setText(_translate("problem", "上一页"))
        self.Jump.setText(_translate("problem", "跳转"))
        self.Choose_reverse.setText(_translate("problem", "反选"))
from qfluentwidgets import CompactSpinBox, PrimaryPushButton, ProgressBar, SearchLineEdit, TransparentPushButton
