# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\LRK\python\ghelper-qt\user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_user(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.AC_Problems = SubtitleLabel(self.centralwidget)
        self.AC_Problems.setText("")
        self.AC_Problems.setObjectName("AC_Problems")
        self.gridLayout.addWidget(self.AC_Problems, 6, 3, 1, 1)
        self.SubtitleLabel_8 = SubtitleLabel(self.centralwidget)
        self.SubtitleLabel_8.setMaximumSize(QtCore.QSize(150, 50))
        self.SubtitleLabel_8.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.SubtitleLabel_8.setObjectName("SubtitleLabel_8")
        self.gridLayout.addWidget(self.SubtitleLabel_8, 9, 2, 1, 1)
        self.SubtitleLabel_4 = SubtitleLabel(self.centralwidget)
        self.SubtitleLabel_4.setMaximumSize(QtCore.QSize(150, 50))
        self.SubtitleLabel_4.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.SubtitleLabel_4.setObjectName("SubtitleLabel_4")
        self.gridLayout.addWidget(self.SubtitleLabel_4, 5, 2, 1, 1)
        self.uid = SubtitleLabel(self.centralwidget)
        self.uid.setText("")
        self.uid.setObjectName("uid")
        self.gridLayout.addWidget(self.uid, 2, 3, 1, 1)
        self.SubtitleLabel_5 = SubtitleLabel(self.centralwidget)
        self.SubtitleLabel_5.setMaximumSize(QtCore.QSize(150, 50))
        self.SubtitleLabel_5.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.SubtitleLabel_5.setObjectName("SubtitleLabel_5")
        self.gridLayout.addWidget(self.SubtitleLabel_5, 6, 2, 1, 1)
        self.HyperlinkButton = HyperlinkButton(self.centralwidget)
        self.HyperlinkButton.setMaximumSize(QtCore.QSize(200, 100))
        self.HyperlinkButton.setObjectName("HyperlinkButton")
        self.gridLayout.addWidget(self.HyperlinkButton, 8, 0, 1, 1)
        self.User_avatar = AvatarWidget(self.centralwidget)
        self.User_avatar.setMinimumSize(QtCore.QSize(200, 200))
        self.User_avatar.setObjectName("User_avatar")
        self.gridLayout.addWidget(self.User_avatar, 4, 0, 3, 2)
        self.SubtitleLabel_7 = SubtitleLabel(self.centralwidget)
        self.SubtitleLabel_7.setMaximumSize(QtCore.QSize(150, 50))
        self.SubtitleLabel_7.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.SubtitleLabel_7.setObjectName("SubtitleLabel_7")
        self.gridLayout.addWidget(self.SubtitleLabel_7, 8, 2, 1, 1)
        self.user = StrongBodyLabel(self.centralwidget)
        self.user.setMaximumSize(QtCore.QSize(100, 16777215))
        self.user.setText("")
        self.user.setObjectName("user")
        self.gridLayout.addWidget(self.user, 2, 1, 1, 1)
        self.Solved = SubtitleLabel(self.centralwidget)
        self.Solved.setText("")
        self.Solved.setObjectName("Solved")
        self.gridLayout.addWidget(self.Solved, 7, 3, 1, 1)
        self.Submit = SubtitleLabel(self.centralwidget)
        self.Submit.setText("")
        self.Submit.setObjectName("Submit")
        self.gridLayout.addWidget(self.Submit, 8, 3, 1, 1)
        self.SubtitleLabel_6 = SubtitleLabel(self.centralwidget)
        self.SubtitleLabel_6.setMaximumSize(QtCore.QSize(150, 50))
        self.SubtitleLabel_6.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.SubtitleLabel_6.setObjectName("SubtitleLabel_6")
        self.gridLayout.addWidget(self.SubtitleLabel_6, 7, 2, 1, 1)
        self.SubtitleLabel_3 = SubtitleLabel(self.centralwidget)
        self.SubtitleLabel_3.setMaximumSize(QtCore.QSize(150, 50))
        self.SubtitleLabel_3.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.SubtitleLabel_3.setObjectName("SubtitleLabel_3")
        self.gridLayout.addWidget(self.SubtitleLabel_3, 4, 2, 1, 1)
        self.SubtitleLabel = SubtitleLabel(self.centralwidget)
        self.SubtitleLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.gridLayout.addWidget(self.SubtitleLabel, 2, 0, 1, 1)
        self.SubtitleLabel_2 = SubtitleLabel(self.centralwidget)
        self.SubtitleLabel_2.setMaximumSize(QtCore.QSize(150, 50))
        self.SubtitleLabel_2.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.gridLayout.addWidget(self.SubtitleLabel_2, 2, 2, 1, 1)
        self.Username = SubtitleLabel(self.centralwidget)
        self.Username.setText("")
        self.Username.setObjectName("Username")
        self.gridLayout.addWidget(self.Username, 4, 3, 1, 1)
        self.Rank = SubtitleLabel(self.centralwidget)
        self.Rank.setText("")
        self.Rank.setObjectName("Rank")
        self.gridLayout.addWidget(self.Rank, 5, 3, 1, 1)
        self.Rate = SubtitleLabel(self.centralwidget)
        self.Rate.setText("")
        self.Rate.setObjectName("Rate")
        self.gridLayout.addWidget(self.Rate, 9, 3, 1, 1)
        self.SubtitleLabel_9 = SubtitleLabel(self.centralwidget)
        self.SubtitleLabel_9.setMaximumSize(QtCore.QSize(150, 16777215))
        self.SubtitleLabel_9.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.SubtitleLabel_9.setObjectName("SubtitleLabel_9")
        self.gridLayout.addWidget(self.SubtitleLabel_9, 10, 2, 1, 1)
        self.Description = SubtitleLabel(self.centralwidget)
        self.Description.setText("")
        self.Description.setObjectName("Description")
        self.gridLayout.addWidget(self.Description, 10, 3, 1, 1)
        self.Search_user = SearchLineEdit(self.centralwidget)
        self.Search_user.setMaximumSize(QtCore.QSize(150, 33))
        self.Search_user.setObjectName("Search_user")
        self.gridLayout.addWidget(self.Search_user, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SubtitleLabel_8.setText(_translate("MainWindow", "Rate:"))
        self.SubtitleLabel_4.setText(_translate("MainWindow", "Rank:"))
        self.SubtitleLabel_5.setText(_translate("MainWindow", "AC Problems:"))
        self.HyperlinkButton.setText(_translate("MainWindow", "Hyperlink button"))
        self.SubtitleLabel_7.setText(_translate("MainWindow", "Submit:"))
        self.SubtitleLabel_6.setText(_translate("MainWindow", "Solved:"))
        self.SubtitleLabel_3.setText(_translate("MainWindow", "Username:"))
        self.SubtitleLabel.setText(_translate("MainWindow", "用户："))
        self.SubtitleLabel_2.setText(_translate("MainWindow", "uid:"))
        self.SubtitleLabel_9.setText(_translate("MainWindow", "Description:"))


from qfluentwidgets import (
    AvatarWidget,
    HyperlinkButton,
    SearchLineEdit,
    StrongBodyLabel,
    SubtitleLabel,
)
